web:
  build: .
  dockerfile: docker/production/Dockerfile
  volumes:
    - hcpl-production-assets:/app/public/assets
    - /mnt/disk/apps/hcpl/shared/public/system:/app/public/system
    - /mnt/disk/apps/hcpl/shared:/shared
    - /mnt/disk/apps/hcpl/shared/log:/app/log
  restart: always
  env_file: /mnt/disk/apps/hcpl/shared/secrets.env
  command: bundle exec puma -C config/puma.rb
  cpu_quota: 25000
  mem_limit: 800M
  links:
    - postgres
    - redis
  expose:
    - "3000"
  ports:
    - 127.0.0.1:3000:3000

sidekiq:
  build: .
  dockerfile: docker/production/Dockerfile
  cpu_quota: 100000
  mem_limit: 900M
  restart: always
  env_file: /mnt/disk/apps/hcpl/shared/secrets.env
  volumes:
    - /mnt/disk/apps/hcpl/shared/public/system:/app/public/system
    - /mnt/disk/apps/hcpl/shared:/shared
    - /mnt/disk/apps/hcpl/shared/log:/app/log
  command: bundle exec sidekiq --config config/sidekiq.yml
  links:
    - postgres
    - redis

postgres:
  image: postgres:9.6
  ports:
    - "5432"
  environment:
    - POSTGRES_DB=hcpl
  volumes:
    - '/mnt/disk/apps/hcpl/shared/postgres:/var/lib/postgresql/data'

redis:
  image: redis:3.2-alpine
  ports:
    - "6379"
  volumes:
    - '/mnt/disk/apps/hcpl/shared/redis:/var/lib/redis/data'
