web:
  build: ../../
  dockerfile: Dockerfile
  volumes:
    - hcpl-production-assets:/app/public/assets
    - /home/mbajur/hcpl/shared:/shared
    - /home/mbajur/hcpl/shared/log:/app/log
  # hostname: "netguru.hcpl.production.web"
  restart: always
  env_file: /home/mbajur/hcpl/shared/secrets.env
  command: bundle exec puma -C config/puma.rb
  cpu_quota: 25000
  mem_limit: 800M
  # labels:
  #   - "mbajur.appname=hcpl"
  #   - "mbajur.stage=production"
  links:
    - postgres
    - redis
  expose:
    - "3000"
  ports:
    - 127.0.0.1:3000:3000

sidekiq:
  build: ../../
  dockerfile: Dockerfile
  cpu_quota: 100000
  mem_limit: 900M
  restart: always
  env_file: /home/mbajur/hcpl/shared/secrets.env
  volumes:
  - /home/mbajur/hcpl/shared:/shared
  - /home/mbajur/hcpl/shared/log:/app/log
  # hostname: "netguru.hcpl.production.sidekiq"
  command: bundle exec sidekiq --config config/sidekiq.yml
  # labels:
  #   - "netguru.appname=hcpl"
  #   - "netguru.stage=production"
  links:
    - postgres
    - redis

postgres:
  image: postgres:9.6
  ports:
    - "5432"
  environment:
    - POSTGRES_DB=hcpl
  volumes:
    - '/home/mbajur/hcpl/shared/postgres:/var/lib/postgresql/data'

redis:
  image: redis:3.2-alpine
  ports:
    - "6379"
  volumes:
    - '/home/mbajur/hcpl/shared/redis:/var/lib/redis/data'
